@startuml
scale 500 width
left to right direction
skinparam linetype ortho

class Identifier{
  -id: int
  -alreadyUsed: Set<int> {static}
  --
}

abstract class Action{
  -id: Identifier
  -affected: Entity
  --
  -Action(_affected: Entity)
  -modify(): boolean {abstract}
}

'Item modifiers
class ChargeModifier{
  -charge: int
  -usableOn: Set<Class> {static}
  --
  -modify(): boolean
}

class OnModifier{
  -isON: boolean
  -usableOn: Set<Class> {static}
  --
  -modify(): boolean
}

class PairedModifier{
  -paired: Item
  -usableOn: Set<Class> {static}
  --
  -modify(): boolean
}

'Room modifiers
class GassedModifier{
  -duration: int
  -usableOn: Set<Class> {static}
  --
  -modify(): boolean
}

class GhostDoorsModifier{
  -duration: int
  -usableOn: Set<Class> {static}
  --
  -modify(): boolean
}


'Human modifiers
class StunnedModifier{
  -duration: int
  -usableOn: Set<Class> {static}
  --
  -modify(): boolean
}

class DeadModifier{
  -usableOn: Set<Class> {static}
  --
  -modify(): boolean
}

class Entity{
  -id: Identifier
  -modifiers: List<Action>
  __
  -delete(): boolean
  -create(): boolean
  -removeModifier(): boolean
}

abstract class Human{
  -inventory: Inventory
  __
  -move(): boolean
  -useItem(): boolean
  -pickUpItem(): boolean
  -dropItem(): boolean
  -dropAllItems(): boolean
  -isStunned(): boolean
}
class Student{
  -isAlive(): boolean
}
class Teacher{
  -kill(): boolean
}
abstract class Item{
  -action: Action
  __
  -use(): boolean {abstract}
}
class Door{
  -target: Room
}
class Room{
 -inventory: Inventory
 -playerList: List<Human>
 -doorList: List<Door>
}
class Inventory{
 -maxSize: int
 -container: List<Item>
 --
 -transferItems(o: itemContainer, ids: List<int>): boolean
}
class Timer{
  -tick()
}

ChargeModifier --|> Action
OnModifier --|> Action
GassedModifier --|> Action
GhostDoorsModifier --|> Action
StunnedModifier --|> Action
DeadModifier --|> Action
PairedModifier --|> Action

Action --* Identifier
Entity --* Identifier
Entity --o Action
Entity <|-- Human
Entity <|-- Item
Entity <|-- Room
Entity <|-- Door
Human <|-- Student
Human <|-- Teacher
Inventory *-- Human
Inventory *-- Room
Item <|-- TVSZ
Item <|-- BeerGlass
Item <|-- Camembert
Item <|-- Mask
Item <|-- Cloth
Item <|-- Transistor
Item <|-- Slipstick
Item o-- Inventory
Door *-- Room
Room o-- Door
Human o-- Room
@enduml