@startuml
'https://plantuml.com/sequence-diagram

title Player uses item - Beer
autonumber

Actor Player as p
 participant Inventory as inven
 participant Item as item
 participant ActionQueue as aq

 p -> inven: selectItem()
activate inven

inven -> item: use()
activate item

item -> aq: addAction(BeerGlassAction)
activate aq
item -> aq: addAction(decreaseDurationAction)
item -> aq: executeAll()
loop action in queue
    aq -> Action: execute()
    activate Action
    Action -> aq: true
    deactivate Action
end loop
return if any of the executes returned false then false, otherwise true
return true
return id: Identifier

@enduml