@startuml
'https://plantuml.com/sequence-diagram

title Player uses item - Camambert
autonumber

Actor Player as p
participant Inventory as inv
participant Item as item
participant ActionQueue as aq
participant Room

p -> inv: selectItem()
activate inv

inv -> item: use()
activate item

item -> aq: addAction(CamambertAction)
activate aq
item -> aq: addAction(DStunAction)
item -> aq: executeAll()

aq -> Room: execute()
activate Room

return true
return true
return true
return id: Identifier


@enduml