@startuml
'https://plantuml.com/sequence-diagram

title Player uses item - Beer
autonumber

Actor Player as p
 participant Inventory as inven
 participant Item as item
 participant ActionQueue as aq

 p -> inven: selectItem()
activate inven

inven -> item: use()
activate item

item-> aq: addAction(decreaseDurationAction)
activate aq
item -> aq: addAction(TickProcessor)
return true
return true
return true

@enduml