@startuml
'https://plantuml.com/sequence-diagram

title Possible actions of item - Beer
autonumber

Actor Player as p
participant Human as h
participant Item as i

p -> h: use(Beer)
activate h
h -> i: use()
activate i
alt on: false
    i <-> h: context.parent.getKillActions().addAction(this)
    i -> i: on = true
else on: true
    alt duration > 0
        i -> i: duration--
    else duration == 0
        i -> h: context.target.getKillActions().removeAction(this)
    end
end

return true
return true

@enduml