@startuml
'https://plantuml.com/sequence-diagram

title Player uses item - Cloth
autonumber

Actor Player as p
participant Inventory as inv
participant Item as item
participant ActionQueue as aq

p->inv : selectItem()
activate inv

inv->item: use()
activate item

item->aq: addAction(dTickProcessorAction)
activate aq
item -> aq: executeAll()
loop action in queue
    aq -> Action: execute()
    activate Action
    Action -> aq: Timer.tick()
    deactivate Action
end loop
return if any of the executes returned false then false, otherwise truereturn true
return true
return id: Identifier
@enduml