@startuml
'https://plantuml.com/sequence-diagram

title Player uses item - Cloth
autonumber

Actor Player as p
participant Inventory as inv
participant Item as item
participant ActionQueue as aq

p->inv : selectItem()
activate inv

inv->item: use()
activate item

item->aq: addAction(decreaseDuartionAction)
activate aq
aq -> item: execute(TickProcessor)
deactivate aq
return true
return true

@enduml