@startuml
'https://plantuml.com/sequence-diagram

title Player uses item - Mask
autonumber

Actor Player as p
participant Inventory as inv
participant Item as item
participant ActionQueue as aq

p -> inv: selectItem()
activate inv

inv -> item: use()
activate item

item -> aq: addAction(MaskAction)
activate aq

item -> aq: addAction(decreaseDurationAction)
item -> aq: executeAll()


loop action in queue
    aq -> Action: execute()
    activate Action
    return true
end loop

return if any of the executes returned false then false, otherwise true

return true

return id: Identifier

@enduml