@startuml
'https://plantuml.com/sequence-diagram

title Possible actions of item - Cloth
autonumber

Actor Player as p
participant Human as h
participant Item as i
participant Room as r

p->h : use(Cloth)
activate h

h -> i: execute()
activate i
alt on: false
    i -> r: getEnterActions().addAction(this)
    activate r
    return true
    i -> i: on = true
    i -> i: putdown()
else on: true
    i -> h: context.target.stun()
    activate h
    return true
end
return true
return true
@enduml