@startuml
'https://plantuml.com/state-diagram
scale 350 width


@startuml
[*] --> Sima_szoba
Sima_szoba --> Gázos_szoba
Gázos_szoba --> Sima_szoba
Sima_szoba --> Eltűnős_szoba
Eltűnős_szoba --> Sima_szoba
Eltűnős_szoba --> Gázos_és_eltünős_szoba
Gázos_és_eltünős_szoba --> Eltűnős_szoba
Gázos_és_eltünős_szoba --> Gázos_szoba
Gázos_szoba --> Gázos_és_eltünős_szoba

Gázos_és_eltünős_szoba --> [*]
Sima_szoba --> [*]
Gázos_szoba --> [*]
Eltűnős_szoba --> [*]
@enduml
