@startuml
'https://plantuml.com/state-diagram
scale 350 width


@startuml
[*] --> Basic_room
Basic_room --> Gassed_room : gas_effect_applies
Gassed_room --> Basic_room : gas_effect_ends
Basic_room --> Ghost_room : ghost_effect_applies
Ghost_room --> Basic_room : ghost_effect_ends
Ghost_room --> Gassed_and_ghost_room : gas_effect_applies
Gassed_and_ghost_room --> Ghost_room : gas_effect_ends
Gassed_and_ghost_room --> Gassed_room : ghost_effect_ends
Gassed_room --> Gassed_and_ghost_room : ghost_effect_applies

@enduml
