@startuml
'https://plantuml.com/state-diagram
scale 350 width


@startuml
[*] --> Basic_state
Basic_state --> Unconscious : gas_effect
Unconscious --> Basic_state : gas_effect_ends

Unconscious --> [*] : win/lose
Basic_state --> [*] : win/lose

@enduml
