@startuml
scale 350 width


@startuml
[*] --> On_the_ground
On_the_ground --> Picked_up : pick_up
Picked_up --> On_the_ground : put_down
state On_the_ground {
 [*] --> Turned_off
 Turned_on --> Turned_off : turn_off
 Turned_off --> Turned_on : turn_on
}


@enduml