@startuml
scale 350 width


@startuml
[*] --> Földön
Földön --> Felvéve
Felvéve --> Földön
state Földön {
 Bekapcsolva --> Kikapcsolva
 Kikapcsolva --> Bekapcsolva
}

Felvéve --> [*]
Földön --> [*]

@enduml