@startuml
'https://plantuml.com/state-diagram
scale 350 width

[*] --> On_the_ground
On_the_ground --> Picked_up : pick_up
Picked_up --> On_the_ground : drop
Picked_up --> Being_used : use
state Being_used {
 [*] --> Valid_for_3_more_occusions
 Valid_for_3_more_occusions --> Valid_for_2_more_occusions : protected_you
 Valid_for_2_more_occusions --> Valid_for_1_more_occusions : protected_you
 Valid_for_1_more_occusions --> Disappear : protected_you
}

Being_used --> [*] : win/lose
Picked_up --> [*] : win/lose
On_the_ground --> [*] : win/lose

@enduml