@startuml
'https://plantuml.com/state-diagram
scale 350 width

[*] --> Földön
Földön --> Felvéve
Felvéve --> Földön
Felvéve --> Használva
state Használva {
 [*] --> Még_3_alkalommal_érvényes
 Még_3_alkalommal_érvényes --> Még_2_alkalommal_érvényes
 Még_2_alkalommal_érvényes --> Még_1_alkalommal_érvényes
 Még_1_alkalommal_érvényes --> Eltűnt
}

Használva --> [*]
Felvéve --> [*]
Földön --> [*]

@enduml