@startuml
'https://plantuml.com/state-diagram
scale 350 width

[*] --> On_the_ground
On_the_ground --> Picked_up : pick_up
Picked_up --> On_the_ground : drop
Picked_up --> Being_used : use
state Being_used {
 [*] --> Valid_for_X_more_occasions
 Valid_for_X_more_occasions  --> Disappear : protected_you [X == 0]
}


@enduml