@startuml
'https://plantuml.com/sequence-diagram

title Player picks up an item
autonumber

Actor Player as P
participant Human as H
participant Item as I
participant Inventory_of_Room as Inv
participant Inventory_of_Human

P->H: pickUpItem()
activate H

H->I: pickUp()
activate I




@enduml