@startuml
'https://plantuml.com/sequence-diagram

title Player moves into gassed room
autonumber

actor Player as p
participant Human as H
participant Door as D
participant Room as R
participant ActionQueue as A

p->H: move()
activate H

H->D: open()
activate D

D->R: enter()
activate R

loop action in queue
    A->action: action.execute()
end loop
activate A
A->R: DEnterAction.execute()

return true
return true

H->H: DStunAction.execute()

return true
@enduml