@startuml
'https://plantuml.com/sequence-diagram

title Player moves into gassed room
autonumber

actor Player as p
participant Human as H
participant Door as D
participant Room as R
participant Action as A

p->H: move()
activate H

H->D: open()
activate D

D->R: enter()
activate R

R->A: RoomAction.execute()
activate A

A->R: DEnterAction.execute()
A->H: DStunAction.execute()
deactivate A

return true
return true
return true

'TODO: All items dropping

@enduml