@startuml
'https://plantuml.com/sequence-diagram
title User drops item in room
autonumber

participant "User" as U
participant "Room" as R

ref over U, R: DRHP

R -> U: sendInventoryList() -> (room_inv)
U -> U: selectItem() -> (Identifier)
U -> U: transferItems(room_inv, Identifier)

@enduml