@startuml
'https://plantuml.com/sequence-diagram
title User steps into a gassed room
autonumber

participant "User" as U
participant "Room" as R

ref over U, R: DRHP
alt Room has GassedModifier
    alt User has no mask
        R -> U: applyModifier(StunnedModifier)
        U -> U: dropAllItems()
    end
end
@enduml