@startuml
'https://plantuml.com/sequence-diagram
title User picks up item from room
autonumber

participant "User" as U
participant "Room" as R

ref over U, R: DRHP

R -> U: sendInventoryList()
U -> U: pickUpItem(I)
U -> R: transferItems(this.inventory, [I])

@enduml