@startuml
'https://plantuml.com/sequence-diagram
title Using transistors
autonumber

actor User as u
participant Trainsistor1 as t1
participant Trainsistor2 as t2
participant NeedsPairingModifier as n
participant PairedModifier as p
participant OnModifier as o

u -> t1: use()
alt t1 has NeedsPairingModifier
    t1 -> n: modify()
    n <-> u: getInventory() -> items
    n -> n: select other transistor (t2)
    alt t2 has NeedsPairingModifier
        n <-> t2: removeModifier(NeedsPairingModifier)
        n <-> t2: addModifier(PairedModifier(t1))
        n -> t1: true
    else t2 has PairedModifier
        n -> t1: false
    end
    alt NeedsPairingModifier returns true
        t1 -> t1: removeModifier(NeedsPairingModifier)
        t1 -> t1: addModifier(PairedModifier(t2))
        t1 -> u: true
    else NeedsPairingModifier returns false
        t1 -> u: false
    end
else t1 has PairedModifier and does not have OnModifier
    t1 -> o: modify()
    o -> u: true
else t1 has PairedModifier and has OnModifier
    t1 -> t1: removeModifier(OnModifier)
    t1 <-> u: dropItem(t1)
    t1 <-> u: setPosition(t2.getPosition())
    t1 -> u: true
end
@enduml