@startuml
'https://plantuml.com/sequence-diagram

autonumber
title Student uses item - Beer
skinparam dpi 600

actor Player as p
participant Student as s
participant Beer as b

p -> s: selectItem(id: int)
activate s

s -> b: execute()
activate b

b -> s: applyEffect(unkillable: Effect)
activate s
return true

return true

return

@enduml