@startuml sequence_diagram

participant Student
participant Room
participant Item
participant ItemContainer

note left of Student: Hallgató felvételi folyamat\na tárgyra

Student -> ItemContainer: pickUpItem(tárgy)
activate ItemContainer
ItemContainer -> Room: getItem(tárgy)
activate Room
Room --> ItemContainer: tárgy
deactivate Room
ItemContainer --> Student: true
deactivate ItemContainer


@enduml
