@startuml
'https://plantuml.com/sequence-diagram

autonumber
title Student drops an item

skinparam dpi 600

actor Player as p
participant Student as student
participant Room as r
participant ItemContainer as inv

p->student: dropItem(item: Item)
activate student

student->r: receiveItem(item: Item)
activate r

r->inv: transferItem(inv: ItemContainer, item: Item)
activate inv

return true
return true
return true
@enduml