@startuml
'https://plantuml.com/sequence-diagram

autonumber
title Student puts on a mask
skinparam dpi 600

actor Player as p
participant Student as s
participant Mask as m

p -> s: selectItem(id: int)
activate s

s -> m: execute()
activate m

m -> s: applyEffect(unstunnable: Effect)
activate s
return true

return true

return

@enduml