@startuml
'https://plantuml.com/sequence-diagram

autonumber
title Student switches rooms
skinparam dpi 600

actor Player as p
participant Student as s
participant Door as d
participant Room as r

p -> s: move(door: Door)
activate s

s -> d: move()
activate d

d -> r: enter()
activate r

return true

return true

return true

@enduml