@startuml
'https://plantuml.com/sequence-diagram

autonumber
title Student moves into gassed room with mask
skinparam dpi 600

actor Player as p
participant Student as s
participant Door as d
participant Room as r

p -> s: move(door: Door)
activate s

s -> d: move()
activate d

d -> r: enter()
activate r

r -> r: affected(gassed: Effect)
activate r

return true

r -> s: applyEffect(stun: Effect)
activate s

s -> s: affected(unstunnable: Effect)
activate s
return true

return false
return true
return true
return true
@enduml