@startuml
'https://plantuml.com/sequence-diagram
title Human applying modifier to room with other humans in it
autonumber

participant "User" as U
participant "Room" as R
participant "Teacher" as T

ref over U, R: DRHP
ref over T, R: DRHP

alt DRHP
    loop player in Room.playerList
      ref over R, player: Kill call on present Humans
    end
end
@enduml