@startuml
'https://plantuml.com/sequence-diagram
title Sequence diagram of using an item with an applicable modifier
autonumber

participant "User" as U
participant "Room" as R
participant "Item" as I

ref over U, R: DRHP

U -> I: use()
alt Item has room applicable modifier
    I <-> U: getPosition() -> room
    I -> R: applyModifier(Item.applicableModifier)
    loop player in Room
        R -> player: applyModifier(Item.applicableModifier.modify)
    end
else Item has player applicable modifier
    I -> U: applyModifier(Item.applicableModifier)
end
@enduml